-- AlterTable
ALTER TABLE "User" ADD COLUMN     "carbsTarget" INTEGER NOT NULL DEFAULT 1750,
ADD COLUMN     "fatTarget" INTEGER NOT NULL DEFAULT 500,
ADD COLUMN     "proteinTarget" INTEGER NOT NULL DEFAULT 1050;
