AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Local Meal CSV parser

Resources:
  MealParserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: handler.handler
      Runtime: nodejs20.x
      Timeout: 30
      Environment:
        Variables:
          PG_URL: ${PG_URL}
      Events:
        MealUpload:
          Type: S3
          Properties:
            Bucket: !Ref UploadsBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .csv

  UploadsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${UPLOAD_BUCKET}
